#The problem asks:
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first
#10 terms will be:
#1,2,3,5,8,13,21,34,55,89
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a, b = 1, 2  # First two numbers of Fibonacci 
total = 0   

while a <= 4000000:
    if a % 2 == 0:  # is number even?
        total += a  # if it is add to total
    a, b = b, a + b  # updates the values of a and b to generate the next Fibonacci numbers.

print(total) # so the answer is "4613732"

